### ISSUE TITLE
wrong arguments passed to buffer::copy

### ISSUE THREAD

**Issue by refack** [wyhaya/updns#7]
Hello @wyhaya there's a bug in
https://github.com/wyhaya/updns/blob/4fb62c6fa6863089c8443d737ad1de61031280af/lib/parse.js#L125-L126
The third argument should be a number indicating `sourceStart`, see https://nodejs.org/api/buffer.html#buffer_buf_copy_target_targetstart_sourcestart_sourceend

**Comment by wyhaya** [comment]
@refack Thank you, this problem does not exist anymore
