### ISSUE TITLE
Malformed packet on binded addresses

### ISSUE THREAD

**Issue by aurelhann** [wyhaya/updns#8]
When I `dig` a specific binded address we have a wrong number of packet in response.
See bellow.

![image](https://user-images.githubusercontent.com/24210502/62416706-1780f400-b640-11e9-9f24-c4cebd432e9f.png)

When i'll do the same `dig` command everything is fine.

**Comment by aurelhann** [comment]
Found !
The command `dig` have additionals records (for dnsec compatibility ;) ) and your parser are not fully compatible with the rfc.
For fix it just fix the qname parsing method like this
```js
    const qnameSize = getStringFrameSize(buf, 12);
    question.qname = buf.slice(12, 12 + qnameSize )

    question.qtype = buf.slice(12 + qnameSize, 12 + qnameSize + 2)
    question.qclass = buf.slice(12 + qnameSize + 2, 12 + qnameSize + 4)
```
in `parse.js` file

and `getStringFrameSize` method is just a method to find the null ending char of the end of dns addr name ;)

enjoy

**Comment by wyhaya** [comment]
@aurelhann Thank you, this problem does not exist anymore
